# .github/workflows/deploy.yml

name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ "master" ] # Trigger the workflow on push to the master branch

env:
  PROJECT_ID: coffee-shop-467807
  REGION: asia-southeast2
  SERVICE_NAME: sentimenkopi-com-prod
  REPO_NAME: sentimenkopi-repo

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: 'github-actions-sa@${{ env.PROJECT_ID }}.iam.gserviceaccount.com'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Configure Docker
      run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

    # --- UPDATED: Tag with the unique Git commit SHA instead of 'latest' ---
    - name: Build Docker image
      run: docker build --no-cache -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }} .

    - name: Push Docker image
      run: docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: ${{ env.SERVICE_NAME }}
        region: ${{ env.REGION }}
        # --- UPDATED: Deploy the new, uniquely tagged image ---
        image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
        env_vars: |
          GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
        flags: >-
          --port=8000
          --memory=2Gi
          --allow-unauthenticated
